name: revert build.ctl file

on:
  pull_request:
    types:
      - closed

jobs:
  revert-file:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github actions"
          git config user.email "actions@github.com"

      - name: checko if buil.ctl was modified in the PR
        id: check-file
        run: |
          git checkout master
          git pull origin master
          git diff --name-only HEAD | grep -q "^build.ctl$" && echo "modified=true" || echo "modified=false"
        shell: bash

      - name: Revert build.ctl to match master
        if: steps.check-file.outputs.modified == 'true'
        run: |
          git checkout origin/master -- build.ctl
          git commit -m "Revert build.ctl to match master"
          git push origin master
