name: revert build.ctl file before merging to master

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  revert_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Git identity
        run: |
          git config user.name "github actions"
          git config user.email "actions@github.com"

      - name: fetch origin master
        run: |
          git fetch origin master

      - name: check if build.ctl has changes
        run: |
          git diff --exit-code origin/master -- build.ctl || echo "build.ctl has changes"

      - name: Revert build.ctl to match master version
        run: |
          git checkout origin/master -- build.ctl

          git diff --exit-code || git commit -m "Revert build.ctl to master version before merge"

      - name: merge pr into master
        run: |
          git checkout master
          git merge --no-ff ${{ github.head_ref }}  --allow-unrelated-histories

      - name: push changes to master
        run: |
          git push origin master
