name: Revert buil.ctl before merging to maser

on:
  pull_request:
    branches:
      - master

jobs:
  revert_file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the pull request branch
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: set up git identity
      run: |
        git config user.name "git hub actions"
        git config user.email "actions@github.com"

    - name: Force replace build.ctl
      run: |
        echo "Forcing replpacement of build.ctl"
        git fetch origin
        git checkout master
        git checkout origin/master -- build.ctl
        git add build.ctl
        git commit -m "force replacement "
        git push origin master

    - name: merge pull request branch
      run: |
        echo "mergin pull request branch"
        git fetch origin
        git checkout master
        git merge --no-ff origin/${{ github.head_ref }}

    - name: push final merge to master
      run:
        git push origin master
