name: revert build.ctl file

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  revert_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Git identity
        run: |
          git config user.name "github actions"
          git config user.email "actions@github.com"

      - name: check if xtl file has changed in the PR branch
        run: |
          git fetch origin master
          git diff --exit-code origin/master -- build.ctl || echo "build.ctl has changes, reverting ..."

      - name: revert built.ctl to match master version
        run: |
          git fetch origin master
          git checkout origin/master -- build.ctl
          git add build.ctl
          git commit -m "Revert build.ctl to match master version after merge"

      - name: merge pr into master
        run: |
          git fetch origin
          git checkout master
          git merge --no.ff ${{ github.head_ref }}

      - name: push changes to master
        run: |
          git push origin master
