name: Revert buil.ctl before merging to maser

on:
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  revert_and_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the pull request branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: set up git identity
      run: |
        git config user.name "git hub actions"
        git config user.email "actions@github.com"

    - name: fetch origin master
      run: |
        git fetch origin master


    - name: checkout if build.ctl has changes
      run: |
        git diff --exit-code origin/master -- build.ctl || echo "build.ctl has changes"

    - name: revert build.ctl to match master
      run: |
        git checkout origin/master -- build.ctl

        git diff --exit-code || git commit -m "Revert build.ctl before merge"

    - name: fetch master branch from remote
      run: |
        git fetch origin master
        git checkout master
        git reset --hard origin/master

    - name: merge pr into master
      run: |
        git checkout master
        git merge --no-ff ${{ github.head_ref }} --allow-unrelated-histories

    - name: push changes to master
      run: |
        git push origin master
