name: Revert buil.ctl before merging to maser

on:
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  protect_build_ctl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the pull request branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: set up git identity
      run: |
        git config user.name "git hub actions"
        git config user.email "actions@github.com"

    - name: fetch origin master
      run: |
        git fetch origin master

    - name: replace build.ctl with master version
      run: |
        echo "forcing replacement of build.ctl with master version"
        git checkout origin/master -- build.ctl
        git add build.ctl
        git commit -m "Force replacement"
        git push origin ${{ github.head_ref }}

    - name: merge branch into master
      run: |
        git checkout master
        git merge --no-ff ${{ github.head_ref}} -m "merge branch into master"
        git push origin master
