name: revert build.ctl file

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  merge_and_revert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: merge pr into master
        run: |
          git fetch origin
          git checkout master
          git merge --no-ff ${{ github.head_ref }}

      - name: revert built.ctl to master version
        run: |
          git checkout origin/master -- build.ctl
          git add build.ctl
          git commit -m "Revert build.ctl to match master version after merge"

      - name: push changes to master
        run: |
          git push origin master
