name: revert build.ctl file

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  revert-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github actions"
          git config user.email "actions@github.com"

      - name: checko if buil.ctl was modified in the PR
        id: check-file
        run: |
          BASE_BRANCH="origin/master"

          git fetch origin
          
          DIFF_FILES=$(git diff --name-only $BASE_BRANCH...HEAD)
          
          if echo "$DIFF_FILES" | grep -q "^build.ctl$"; then
            echo "modified=true"   >> $GITHUB_ENV
          else
            echo "modified=false"  >> $GITHUB_ENV
          fi

      - name: Revert build.ctl tif modified
        if: env.modified == 'true'
        run: |
          git checkout $BASE_BRANCH -- build.ctl
          git add build.ctl
          git commit -m "Revert build.ctl to match master"
          git push origin HEAD
