name: Preserve build.ctl after PM merge

on:
  pull_request:
    types:
      - closed

jobs:
  preserve-build-ctl:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config user.name "github actions"
          git config user.email "actions@github.com"

      - name: fetch master branch
        run: |
          git fetch origin master

      - name: Force replacement of build.ctl with master version
        run: |
          echo "Restoring build.ctl from master branch"
          git checkout origin/master -- build.ctl
          git add build.ctl
          git commit -m "Restore build.ctl to original master versionafter merge"
          git push origin HEAD:master
