name: Revert buil.ctl before merging to maser

on:
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  revert_and_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the pull request branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        #ref: ${{ github.head_ref }}

    - name: set up git identity
      run: |
        git config user.name "git hub actions"
        git config user.email "actions@github.com"

    - name: fetch origin master
      run: |
        git fetch origin master

    - name: checkout if build.ctl has changes
      run: |
        git checkout master
        git merge --no-ff ${{ github.head_ref }} --allow-unrelated-histories || true

    - name: resolve conflicts
      if: failure()
      run: |
        git checkout --ours build.ctl
        git add build.ctl
        git commit -m "Resolve conflicts"

        git push origin master
