name: revert build.ctl file

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  revert-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github actions"
          git config user.email "actions@github.com"

      - name: fetch all remote branches
        run: |
          git fetch origin
        
      - name: checko if buil.ctl was modified in the PR
        id: check-file
        run: |
          BASE_BRANCH="origin/master"
          
          git diff --name-only $BASE_BRANCH...HEAD | grep -q "^build.ctl$" && echo "modified=true" || echo "modified=false"
          echo "modified=$(grep -q "^build.ctl$" && echo true || echo false)" >> $GITHUB_ENV
        shell: bash

      - name: Revert build.ctl tif modified
        if: env.modified == 'false'
        run: |
          git checkout $BASE_BRANCH -- build.ctl
          git commit -m "Revert build.ctl to match master"
          git push origin HEAD
